### ISSUE TITLE
LibUsbDotNet Bulk Transfer Usb Communication Win32Error

### ISSUE THREAD

**Issue by serhanyilmaz** [LibUsbDotNet/LibUsbDotNet#22] opened 2017-10-10 14:13 UTC
We have a vendor-specific device for USB connections.

We used LibUsbDotNet Bulk Transfer communication. In the first case, I did 64 byte data transfer. In the second case I made 1024 byte data transfer. In case of 64 byte transfer, there is usually no problem (Problems are rare). In case of 1024 byte transfer, there is a problem (almost always in USB 2.0 port, also rare in USB 3.0 port) and Finally, when doing USB Write, I get Win32Error error in LibUsbDotNet ErrorCode class.

What causes to this problem

**Comment by seuzht** [comment] 2018-05-12 00:41
Maybe your USBdriver does'not support 1024 bytes length.

**Comment by qmfrederik** [comment] 2018-09-25 15:45
I think this is a duplicate of #23. For this kind of issues, it's better to ask on StackOverflow.

**Closed by qmfrederik** 2018-09-25 15:45 UTC
