### ISSUE TITLE
About the 3.0 version of the nuget package

### ISSUE THREAD

**Issue by GreenShadeZhang** [LibUsbDotNet/LibUsbDotNet#246] opened 2024-06-21 03:32 UTC
I see that the main branch has added a lot of new features, such as support for .net 8 and async. I want to know whether the official has generated new nuget packages for the main branch, because I don’t really want to reference the source code.

**Comment by mcuee** [comment] 2024-06-23 05:41
Duplicate of #230. Please use #230 for discussion.

**Closed by mcuee** 2024-06-23 05:41 UTC
Labels: Build
